# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - NodeWebApplication

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and audit fix
        run: |
          npm install
          npm audit fix || echo "Audit fix encountered issues but continuing build"

      - name: npm build and test
        run: |
          npm run build --if-present
          npm run test --if-present || echo "No tests specified"

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4DBACAD1481467F94D378026D7F34A5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_92F75C727C874C3E8400509DC6AA1FB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AFA806C930C7428AAEE6DB02C35E581F }}

      - name: Set environment variables from env file
        run: |
          while IFS= read -r line; do
            if [[ ! "$line" =~ ^# && -n "$line" ]]; then
              IFS='=' read -ra KV <<< "$line"
              az webapp config appsettings set --name 'NodeWebApplication' --resource-group '<Your-Resource-Group-Name>' --settings "${KV[0]}=${KV[1]}"
            fi
          done < env
        env:
          AZURE_WEBAPP_NAME: 'NodeWebApplication'
          AZURE_RESOURCE_GROUP: '<Your-Resource-Group-Name>'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NodeWebApplication'
          slot-name: 'Production'
          package: .
